import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "ELIETT",
  description: "Generated by ELIETT's team",
  icons: {
    icon: [
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-icon-57x57.png', sizes: '57x57' },
      { url: '/apple-icon-60x60.png', sizes: '60x60' },
      { url: '/apple-icon-72x72.png', sizes: '72x72' },
      { url: '/apple-icon-76x76.png', sizes: '76x76' },
      { url: '/apple-icon-114x114.png', sizes: '114x114' },
      { url: '/apple-icon-120x120.png', sizes: '120x120' },
      { url: '/apple-icon-144x144.png', sizes: '144x144' },
      { url: '/apple-icon-152x152.png', sizes: '152x152' },
      { url: '/apple-icon-180x180.png', sizes: '180x180' },
    ],
  },
};


export const guidaMono = localFont({
  src: [
    {
      path: '/fonts/GuidaMonoPro-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoPro-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoPro-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoPro-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-guida-mono'
});

export const guidaMonoSharp = localFont({
  src: [
    {
      path: '/fonts/GuidaMonoSharpPro-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoSharpPro-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoSharpPro-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoSharpPro-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-guida-mono-sharp'
});



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${guidaMono.variable} ${guidaMonoSharp.variable}`}
    >
      <head>
        <meta charSet="utf-8" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
