import type { Metadata } from 'next';
import { guidaMono, guidaMonoSharp } from './fonts';
import './globals.css';

export const metadata: Metadata = {
    title: 'ELIETT',
    description: "Generated by ELIETT's team",
    icons: {
        icon: [
            {
                url: '/favicon-16x16.png',
                sizes: '16x16',
                type: 'image/png',
            },
            {
                url: '/favicon-32x32.png',
                sizes: '32x32',
                type: 'image/png',
            },
            {
                url: '/favicon-96x96.png',
                sizes: '96x96',
                type: 'image/png',
            },
        ],
        apple: [{ url: '/apple-icon-180x180.png', sizes: '180x180' }],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={` ${guidaMono.variable} ${guidaMonoSharp.variable}`}>
            <head>
                <meta charSet='utf-8' />
            </head>
            <body>{children}</body>
        </html>
    );
}
