import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "ELIETT",
  description: "Generated by ELIETT's team",
};


export const guidaMono = localFont({
  src: [
    {
      path: '/fonts/GuidaMonoPro-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoPro-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoPro-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoPro-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-guida-mono'
});

export const guidaMonoSharp = localFont({
  src: [
    {
      path: '/fonts/GuidaMonoSharpPro-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoSharpPro-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoSharpPro-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '/fonts/GuidaMonoSharpPro-Black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-guida-mono-sharp'
});



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${guidaMono.variable} ${guidaMonoSharp.variable}`}
    >
      <head>
        <meta charSet="utf-8" />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
